Landing Page
anushkumar27/hawker_hub pull request #3
Opened 2022-11-14 22:48 UTC by anushkumar27

# Proposed Changes

Implementation of Landing Page View (view only), its implemented as a stateless widget the functionality is added post completing all the relevant views.

|Figma Design| Flutter Implementation|
|---|---|
|![image](https://user-images.githubusercontent.com/13307985/201783561-281dfdad-7af4-48a3-80f7-78e8f39559f8.png)|![image](https://user-images.githubusercontent.com/13307985/201783303-fef6dae8-5cd6-45ee-bd80-4456b7f66305.png)|

# Jira Stories

- [LAB-315](https://oregonstate-innovationlab.atlassian.net/browse/LAB-315)

# Checklist

- [x] This has been tested
- [x] Self-documenting code
- [x] Code is linted

# Instructions to review
Code inspection and feedback

2022-11-14 23:53 UTC, wbraynen commented on lib/screens/home_screen.dart
> +  double _fabHeight = 0;
What is "fab"?

2022-11-15 00:14 UTC, anushkumar27 commented on lib/screens/home_screen.dart
> +  double _fabHeight = 0;
Floating Action Button (FAB) - In this case, it's the "Contribute +" button that needs to be moved up and down based on the sliding bottom panel.

2022-11-15 04:03 UTC, wbraynen requested changes
Chatted with @anushkumar27 and we decided he'll try self-documenting code and see how it feels.  If it doesn't make things better, then never mind :).

Self-documenting code:
https://stackoverflow.com/questions/209015/what-is-self-documenting-code-and-can-it-replace-well-documented-code
See the answer with 407 upvotes

Not sure this is an example you should be following as role model, but if you are curious, there is also this sort of production code:
https://github.com/google/tcmalloc

2022-11-15 04:03 UTC, wbraynen commented on lib/screens/home_screen.dart
> +                })),
Would it be better to make it self-documenting?  For example:
```
 onPanelSlide: (double position) => setState(() {
        updateContributeButton(position)
      })),
```

2022-11-15 04:03 UTC, wbraynen commented on lib/screens/home_screen.dart
> +  }
Maybe more self documenting?  Would it be clearer if we wrote something like the following instead?

```
  @override
  Widget build(BuildContext context) {
    _explorationPanelHeightOpen = MediaQuery.of(context).size.height * .50;

    let explorationPanel = SlidingUpPanel(
        maxHeight: _explorationPanelHeightOpen,
        minHeight: _explorationPanelHeightClosed,
        parallaxEnabled: true,
        parallaxOffset: .5,
        renderPanelSheet: false,
        panel: _floatingPanel(context),
        collapsed: _floatingCollapsed(context),
        body: GoogleMap(
          onMapCreated: _onMapCreated,
          initialCameraPosition: CameraPosition(
            target: _center,
            zoom: 11.0,
          ),
        ),
        onPanelSlide: (double position) => setState(() {
              udpateContributeButtonPosition(position)
        })
    )

    let contributeButton = Positioned(
      right: 20.0,
      bottom: _fabHeight,
      child: FloatingActionButton.extended(
        onPressed: () {
          // Add your onPressed code here!
        },
        label: const Text('Contribute'),
        icon: const Icon(Icons.add),
      )
    )

    let searchBox = Container(
        margin: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 20.0),
        child: const TextField(
            autofocus: false,
            decoration: InputDecoration(
              hintText: "Name, Category, Food trucks..",
              prefixIcon: Icon(Icons.search),
              suffixIcon: Icon(Icons.cancel_outlined),
              filled: true,
              fillColor: Colors.white,
              border: OutlineInputBorder(),
              labelText: 'Search',
        ))
    )

    return Stack(
      alignment: Alignment.topCenter,
      children: <Widget>[
        explorationPanel,
        contributeButton,
        searchBox
      ]
    );
  }
```

2022-11-15 04:03 UTC, wbraynen commented on lib/screens/home_screen.dart
> +        ],
Clean up the same way, so it's not so mysterious and intimidating (wall of text and all)?

2022-11-15 04:03 UTC, wbraynen commented on lib/widgets/horizontal_card.dart
> +            children: [
More children!  Name your children!  Here and elsewhere.

2022-11-15 21:46 UTC, wbraynen approved these changes
🎉

2022-11-15 21:49 UTC, wbraynen commented
I do recommend pressing "squash and merge" for this when you merge this PR.

2022-11-15 22:15 UTC, merged